### ISSUE TITLE
编译时出现以下错误

### ISSUE THREAD

**Issue by enquan** [NeroAsmarr/xihua#1]
系统环境：Windows 10 Pro 1809 + Python 3.7.5 + Anaconda 2019.10

Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    long_description = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 41: illegal multibyte sequence
![2020-01-03_175524](https://user-images.githubusercontent.com/3251317/71717204-3fc08900-2e52-11ea-8d1c-ab4d6c6d801e.jpg)

**Comment by whliao5am** [comment]
1. 是否出现中文路径
2. 尝试修改setup.py 中的 `with open('README.md', 'r') as f:`为`with open('README.md', 'r',  encoding='utf-8') as f:`
3. 删除setup.py中有关long_description的行，即3，4，13，14行。

暂时没有windows机器，如果上面方法有效，或者自己找到方法解决，可以继续说明，后面将提交修改。

**Comment by Qfrost911** [comment]
将第三行改成如下即可解决
`with open('README.md', 'r',errors="ignore") as f:`
