### ISSUE TITLE
运行范例程序时出现以下错误

### ISSUE THREAD

**Issue by ulysses936** [NeroAsmarr/xihua#2]
File "C:\Users\Administrator\Desktop\zfnew-0.0.3\zfnew\api\login.py", line 30, in login
    tokens = soup.find(id='csrftoken').get("value")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by whliao5am** [comment]
请问是新版教务系统么？如果确定是，可以将教务系统网页私发到我的github主页邮箱，我查看一下网页结构

**Comment by zz6768** [comment]
我运行也是这种错误，有办法解决吗
 File "F:\ym2\zfnew\zfnew-master\zfnew\api\login.py", line 28, in login
    tokens = soup.find(id='csrftoken').get("value")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by NeroAsmarr** [comment]
请问是新版教务系统么？如果确定是，可以将教务系统网页私发到我的github主页邮箱，我查看一下网页结构。
通常情况下，同样的系统应该没有问题，但是不排除特殊情况

**Comment by whliao5am** [comment]
> 我运行也是这种错误，有办法解决吗
> File "F:\ym2\zfnew\zfnew-master\zfnew\api\login.py", line 28, in login
> tokens = soup.find(id='csrftoken').get("value")
> AttributeError: 'NoneType' object has no attribute 'get'

请问是新版教务系统么？如果确定是，可以将教务系统网页私发到我的github主页邮箱，我查看一下网页结构。
通常情况下，同样的系统应该没有问题，但是不排除特殊情况

**Comment by zz6768** [comment]
> > 我运行也是这种错误，有办法解决吗
> > 文件“ F：\ ym2 \ zfnew \ zfnew-master \ zfnew \ api \ login.py”，第28行，位于登录
> > 令牌= soup.find（id ='csrftoken'） .get（“ value”）
> > AttributeError：“ NoneType”对象没有属性“ get”
> 
> 请问是新版教务系统么？如果确定是，可以将教务系统网页私发到我的github主页邮箱，我查看一下网页结构。
> 通常情况下，同样的系统应该没有问题，但是不排除特殊情况
好像不是新版的

**Comment by whliao5am** [comment]
> > > 我运行也是这种错误，有办法解决吗
> > > 文件“ F：\ ym2 \ zfnew \ zfnew-master \ zfnew \ api \ login.py”，第28行，位于登录
> > > 令牌= soup.find（id ='csrftoken'） .get（“ value”）
> > > AttributeError：“ NoneType”对象没有属性“ get”
> > 
> > 
> > 请问是新版教务系统么？如果确定是，可以将教务系统网页私发到我的github主页邮箱，我查看一下网页结构。
> > 通常情况下，同样的系统应该没有问题，但是不排除特殊情况
> > 好像不是新版的

旧版以后可能会支持
