### ISSUE TITLE
弄了很久终于和我们学校兼容了orz发现了以下问题，希望可以提供帮助

### ISSUE THREAD

**Issue by maxchang3** [NeroAsmarr/xihua#3]
安装遇到了阻碍，看了下之前的issu终于是弄好了。
但是直接按例程调用，不行。
仔细检查发现我们学校的教务系统是装到一个二级目录下的。
比如大家可能都是http://example.edu.cn/xtgl/……
而我们是http://example.edu.cn/二级目录/xtgl/
检查源码后发现这个库的逻辑是base_url后面加对应的后缀，这里是包含xtgl的
但是即使我把url写为http://example.edu.cn/二级目录/也是不行的
所以只能把二级目录手工加到源码的各个/xtgl之前。

但是这样还是不能正常获取。
经过排查后发现个人信息的json对应的一些信息项我们学校和这里写的是有差别的 部分信息项对应名称不同，甚至没有，根据自己学校接口的修改好即可。

之后可以正常获取时间表，个人信息等
但是在获取成绩这边给了post传递参数过多的报错。
看了下是get_info.py下的129行
`res = requests.post(self, url, headers=self.headers, data=data, cookies=self.cookies)`
经过和其他方法比较发现前面多了个self，删掉就行了，不知道是不是我们学校系统的原因。

**Comment by whliao5am** [comment]
感谢✅
